projectName: 'backend-project'
namespace: 'backend-project'

replicaCount: 2

image:
  repository: hiremostafa/express-demo
  pullPolicy: Always
  tag: "1.0.1"
  container_port: 3006

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: 'nginx'
  hostname: 'd15.demo-project.xyz'

tlsCertificate:
  certificateEnabled: true
  issuerEnabled: true
  email: 'hiremostafa@gmail.com'
  organization: 'demo-project'
  hostname: 'd15.demo-project.xyz'
