projectName: 'backend-project'
namespace: 'backend-project'

replicaCount: 2

image:
  repository: hiremostafa/express-demo
  pullPolicy: Always
  tag: "1.0.2"
  container_port: 3006

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  ingressClassName: 'nginx'
  hostname: 'd17.demo-project.xyz'

tlsCertificate:
  certificateEnabled: false
  issuerEnabled: true
  email: 'hiremostafa@gmail.com'
  organization: 'demo-project'
  hostname: 'd17.demo-project.xyz'
