{{- if .Values.tlsCertificate.certificateEnabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.projectName }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ .Values.tlsCertificate.organization }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.tlsCertificate.hostname }}
  issuerRef:
    name: {{ .Values.projectName }}
    kind: Issuer
    group: cert-manager.io
{{- end }}