{{- if .Values.tlsCertificate.issuerEnabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.tlsCertificate.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.ingressClassName }}
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
                nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
      selector:
        dnsNames:
        - {{ .Values.tlsCertificate.hostname }}
{{- end }}