apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.projectName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.container_port }}
  selector:
    app: {{ .Values.projectName }}
